### PR TITLE
Fixed font setting not being able to save

### LINKED ISSUE #281: Chat font settings don't stick
When adjusting chat message input and output font size or font on Mac OS Catalina, any changes vanish immediately upon closing the window. As a minor additional piece, all settings in the font menu are in German.

Recording of issue

### PR DESCRIPTION
**Pull request by NoahSaso**
Fixes #281 
There were two variables flipped around :P

### CODE REVIEW

**Comment by Et0h** [comment]
Cheers for figuring this out :)

**Comment by NoahSaso** [comment]
No problem! Should I build the production app and just use it myself or are updates periodically released?

**Comment by Et0h** [comment]
https://bintray.com/syncplay/Syncplay/Syncplay/v1.6.5#files is set to automatically update every time there is a change to v1.6.5, so you can go there for now rather than building yourself. We're hoping to get a release candidate out for Synclay 1.6.5 before the end of the month.

**Comment by NoahSaso** [comment]
Oh super cool! Thank you :)

**Pull request merged**
