### PR TITLE
Added French Translation

### PR DESCRIPTION
**Pull request by sosie-js**
The rabbit has produced [the french translation file  for the Gui](https://github.com/sosie-js/syncplay/blob/frenchbunny/syncplay/messages_fr.py) with the private tool (messages_en.py -> messages2ass.py -> fastrad -> ass2messages.py -> messages_fr.py ) and [the doc](http://sosie.sos-productions.com/gift/syncplay-gui-snapshot-fr.pdf).

### CODE REVIEW

**Comment by Et0h** [comment]
Hi, thanks for providing a French translation of Syncplay.

I note that you have a translation into French for the main Syncplay application, but not for the installer. See https://github.com/Syncplay/syncplay/pull/364/files for the Turkish translation pull request as it is a good example of the changes to buildPy2exe.py and other files.

The pull request should contain just the translations into French.

In terms of changes to the translation system (e.g. to use .ass files), this is completely separate from the French translation itself and should not be in the pull request.

In terms of documentation files for translations, this is not something we do. Attribution is given through commit messages and this is then used to inform https://syncplay.pl/about/development/ and https://syncplay.pl/changelog/

**Comment by sosie-js** [comment]
Oh I wondered what was buildPy2exe.py for. Okay using  .ass was the sugar for others who don't want spend ages
to translate your stuff, I will remove it for the french translation pull request.

**Comment by Et0h** [comment]
> Yout mean the pdf here?

Yes - we don't have documentation within Syncplay to tell people what a translation looks like. It is useful to know that you have tested the translation and it works, but it should be removed from the PR to be in line with other translation PRs.

**Comment by sosie-js** [comment]
>Yes - we don't have documentation within Syncplay to tell people what a translation looks like. It is useful to >know that you have tested the translation and it works, but it should be removed from the PR to be in line with >other translation PRs.
Ok I remove it, my goal was not I to force people of others translation to do so but having [a good overview of Gui at least in English](http://sosie.sos-productions.com/gift/syncplay-gui-snapshot-fr.pdf) should have promote this project as the same time.

**Comment by Et0h** [comment]
Hi @sosie-js  and sorry about the lateness of my reply - I finally have a day when I'm free to go through the various PRs and issues that have built up.

I've reviewed your PR and it looks almost ready for merge, but it needs one final tweak: `syncplay/messages_fr.py` has messages at the beginning, which isn't something which we have for the other translations. If those can be removed then I think it's ready for merging. Thanks again for your work on this translation.

**Comment by sosie-js** [comment]
I will ha a look asap

**Comment by sosie-js** [comment]
Should match your requirement now.

**Pull request merged**
