### PR TITLE
Show servers own ip address and port

### PR DESCRIPTION
**Pull request by abhsag24**
displays local ip's by seeing all interfaces and excluding loopback, and non consequential ip's(that start with, 169.254)
displays the ip of network by, connecting to syncplay.pl, and then gethostname, will change to twisted way, if it is important.

### CODE REVIEW

**Comment by Et0h** [comment]
Thanks for your contribution. Does this connect to syncplay.pl without asking for the user's permission or giving them an opt-out? If so, I'm not happy about that element of it for the reasons stated at #80 (i.e. that "it might not be a good idea to connect to an external IP without user's consent for privacy reasons")

**Comment by Et0h** [comment]
I also note that it would also ideally want any messages moved to messages.py with appropriate stubs so as to be compatible with Syncplay's support for languages other than English.

**Comment by abhsag24** [comment]
At, the moment it does'nt give an opt-out, i'll move the messages in the next commit, what do you propose should be the ideal way of having an opt-out through raw_input, or the arg_parser?

**Comment by Et0h** [comment]
In relation to consent I think an opt-in would be better. In terms of how, Syncplay already uses argparser for command line options, so we just need something like --determine-ip with appropriate explanation of what that means in terms of connecting to Syncplay.pl on the website and the --help descriptions.

Obviously there is then the possibility that someone won't be aware of the feature if they don't run --help and don't visit the website. One way around this would be to link people to http://syncplay.pl/guide/server/ in the welcome messages (e.g. "You are now running a Syncplay v{} server instance on port {}. Visit http://syncplay.pl/guide/server/ to learn more about running a server.")

**Comment by abhsag24** [comment]
in addition to the welcome note, I also think  it would be a nice idea, to tell people to use --determine-ip,to know public ip, and --help to know more, at the place where it generally displays the network-ip.

**Comment by Et0h** [comment]
Sounds reasonable, although if we're going that far it might be better just to list all of the command line arguments/options as there aren't that many of them.

**Comment by abhsag24** [comment]
i'll get to displaying everything later right now it displays the earlier message

**Comment by abhsag24** [comment]
also the constructor of  syncFactory in server.py is kind of getting messy, wouldn't it be better if we use *args,**kwargs instead of listing everything out?

**Comment by Et0h** [comment]
The stubs for non-English messages should be the English message with a #TODO: Translate into Russian/German comment. I can merge and fix that if needed though, so long as people are otherwise happy with this PR.

**Comment by abhsag24** [comment]
i tested the code through an NAT and found that the displayPublicIP() function, doesn't return the public ip, rather it only returns the ip through which, the current request was made, and that the only way to know the public ip is to query a web server. Keeping this in mind, we can 

1> Query a web service(since we already give an opt-in , we can tell the users that we will attempt to connect them to the web service), generally these services follow certain standards, and give the ip's for scripting purposes as well.

2> Query syncplay.pl and have the syncplay server return the ip .

3> We could leave the code as it is and just change the function name, as right now the message
reads "Your active internet ip is {}."  which is still the case, even though it wasn't exactly what we thought.

**Comment by Uriziel** [comment]
Hey, I thought about your PR for a while and what if IP check actually was outside of main code but rather executed different routine upon `./syncplayServer.py --my-ip` displaying IP and exiting.

So it would be possible to check your IP whether your server is running or not + it would not change much of existing code.

Also I think querying syncplay.pl might be the easiest thing to do, we can set up action on webserver that'd return just that.

**Comment by Et0h** [comment]
Have now created http://syncplay.pl/getipaddress/ which provides a JSON along the lines of:

{
your-ip: 1.2.3.4
}

**Comment by abhsag24** [comment]
@Uriziel that would be cool! , though wouldnt it be unrelated to the syncplay software?

**Comment by Uriziel** [comment]
It kinda is already, right?

**Comment by abhsag24** [comment]
@Uriziel right now its a feature for the syncplayServer(part of the software) IMO

**Pull request closed without merging**
