### PR TITLE
Implement Chat: Clients able to send messages in a room

### PR DESCRIPTION
**Pull request by abhsag24**
refinements are still left such as, username is not displayed, the basic framework is done.

### CODE REVIEW

**Comment by abhsag24** [comment]
unicode text is working.

**Comment by abhsag24** [comment]
The current problem in chat is, there is 
1.No UI to send Chat messages, right now.
2.if user types large messages, they are displayed on the screen, which disturbs the viewing experience

To tackle this problem we can 
a. Stop displaying messages in the player altogether 
or
b. Limit the length of message so that they are unobtrusive on the player (preferred)
or
c. Give the power to the client to stop displaying message on the screen in real time.

**Comment by Uriziel** [comment]
You have to rebase your changes away from your other PR though.

**Comment by abhsag24** [comment]
rebased the changes the away.

**Comment by abhsag24** [comment]
another way we could stop large messages from displaying on the player is after a limit we could display only a certain part of the message, followed by "..." , rest of it could be read within the client or on the console

**Comment by Uriziel** [comment]
How are you going to determine what's big message? (i.e. difference between fullHD and laptop screen)

**Comment by abhsag24** [comment]
a full hd screen can have more characters , but displaying a part of the message would only serve as a kind of notification,  so displaying less characters on a bigger screen is not a big deal IMO.

**Comment by remimarenco** [comment]
Hey @abhsag24 , would be glad to help you on this!

**Comment by abhsag24** [comment]
@remimarenco would love to have help, as you can see i had already listed out the things that needed to be done further. What do you suggest?

**Comment by remimarenco** [comment]
@abhsag24 We should take some time to discuss about your vision on your branch, and see how we can work together on this.
Personally, I just want to be able to chat with my loved one while we are watching the movie. Annoying to have to use a third party system or to speak.

I found the [letsgaze](https://letsgaze.com/) system pretty handy to handle the chat

**Comment by perfectcolors** [comment]
I'm really looking forward to this functionality. I think having the conversation more closely tied with the on-screen action is essential for making it a more social experience.

Using Skype works and all, but I agree with @remimarenco that it's not always ideal to be on voice or to have to rely on another program to send text which requires keeping another window / screen active.

**Comment by abhsag24** [comment]
@perfectcolors  @remimarenco i think i've added the basic chat functionality in this PR already, you can go ahead and use it, but you'll have to chat from within the terminal and there are some concerns that i had stated earlier, i don't know much about the GUI and don't have the time right now add that functionality :(  , but it should be pretty usable :)

**Comment by Et0h** [comment]
Merged into https://github.com/Syncplay/syncplay/tree/chat

**Comment by abhsag24** [comment]
awesome! so should i close this PR?

**Comment by Et0h** [comment]
Closing this as PR has been accepted onto the chat branch.

**Pull request closed without merging**
