### PR TITLE
Room history

### PR DESCRIPTION
**Pull request by Gbd199**

### CODE REVIEW

**Comment by Et0h** [comment]
Hi,

I have long wanted for a feature such as this so thanks for helping to move it forwards.

Firstly, I've tested and it works. The behaviour is that it lists the rooms you connect to the server with and then provides them as options from the GuiConfig window for future connections, irrespective of server. As far as it goes, this is a reasonable behaviour because trying to make it per-server arguably adds unnecessary complexity when people might use the same room names across multiple servers

Suggestions for consideration/discussion:
* The ability to delete a room from the list of rooms.
* Allow users to select from the list of rooms once connected, e.g. by making the textbox in the main Syncplay window next to 'Join room' also be a combo box.
* Remember rooms you connect to from the main Syncplay window
* When you create a managed room, also remember the version with the auto-identification in it, e.g. +RoomName:868A81271506:NX-914-891
* An alternative approach to auto-remembering the room names would be to have a 'favourites' system where, once connected, you can add a room to your list of favourites and then manage that list. This will prevent the list from getting clogged up so requires less user action to clear it, but on the other hand does require users to manually click to remember a room which they might forget to do. Which is more convenient and intuitive?

**Comment by Gbd199** [comment]
thanks for the feedback, I'll see what I can do over the weekend

**Comment by Gbd199** [comment]
I decided to go with a dialog for the rooms. This gives the user complete and simple control over the rooms and did not require too many changes. Due to the simple control I think adding a 'favorite rooms' mechanism is pointless.

**Comment by Et0h** [comment]
Allowing people to edit, add and delete rooms via a multiline textbox dialog makes sense, not least because it is in line with what we do for trusted domains and the playlist. I'll try out your latest version and give it some consideration. Something I'll be thinking about is whether there needs to be an easy way to enable/disable the feature automatically remembering room names.

**Comment by Et0h** [comment]
Thought about it, and I think the only thing it really needs is to be able to turn off auto-remembering. If nobody has any further comments/objections then when I have time I'll merge the changes and add any final tweaks myself.

**Comment by Et0h** [comment]
Further discussion take take place on #336

**Pull request merged**
