### PR TITLE
In-player chat input/output support for mpv (feedback wanted)

### PR DESCRIPTION
**Pull request by Et0h**
Allows for inputting US-ASCII characters for mpv and outputting chat in 'chat room' or 'scrolling' styles. Still a few issues to be sorted out (messages containing '\\'), but feedback wanted. Includes a new 'chat' section in the config dialogue. As an experimental feature, you can type in CLI commands by prefixing chat messages with '/'.

### CODE REVIEW

**Comment by Et0h** [comment]
Portable version for Windows: http://syncplay.pl/syncplay_v1.5.2_2017-12-30_Portable.zip
.dmg for OS X available from: https://bintray.com/syncplay/Syncplay/download_file?file_path=Syncplay_chat-osd_macOS.dmg

**Comment by alby128** [comment]
Maybe you should add .appveyor.yml to chat-osd before merging. Also, there are 13 commits that chat-osd should still miss, maybe we should give a look to them.

**Comment by Et0h** [comment]
@alby128: I think all of the conflicts can just be handled when I merge it.

**Comment by Et0h** [comment]
Syncplay 1.5.2 beta 1 is now available from http://syncplay.pl/syncplay-1-5-2-beta-1-enhanced-mpv-chat-support/

**Pull request closed without merging**
