### PR TITLE
Fix broken macOS check

### PR DESCRIPTION
**Pull request by luk1337**

### CODE REVIEW

**Comment by luk1337** [comment]
Before:
Screenshot_20240716_005940

After:
Screenshot_20240716_005931

**Comment by selurvedu** [comment]
@luk1337 you posted the same screenshot twice.

**Comment by luk1337** [comment]
> @luk1337 you posted the same screenshot twice.

no, look at the highlighted part:
image

**Comment by selurvedu** [comment]
Oooh, riiight. That's so hard to notice if you don't know where to look. Sorry for the noise. :sweat_smile:

**Comment by luk1337** [comment]
> Oooh, riiight. That's so hard to notice if you don't know where to look. Sorry for the noise. 😅

np, you can also notice that SSL icon has different style ^^

**Comment by Et0h** [comment]
The fix looks good on Windows, but we have not tested it on macOS and the first change seems to be targeted at that OS. Have you tested your first change on macOS to confirm it fixes an issue rather than introducing one?

**Comment by luk1337** [comment]
> The fix looks good on Windows and Linux, but we have not tested it on macOS and the first change seems to be targeted at that OS. Have you tested your first change on macOS to confirm it fixes an issue rather than introducing one?

ok, I tested it on macOS and this was breaking it, so I just restored it to how it was before.

```
if isMacOS():
    window.outputlabel.setMinimumHeight(21)
else:
    window.outputlabel.setMinimumHeight(27)
```

And with just fixing broken macOS check, this change now only affects non-macOS.

**Comment by luk1337** [comment]
> > The fix looks good on Windows and Linux, but we have not tested it on macOS and the first change seems to be targeted at that OS. Have you tested your first change on macOS to confirm it fixes an issue rather than introducing one?
> 
> ok, I tested it on macOS and this was breaking it, so I just restored it to how it was before.
> 
> ```
> if isMacOS():
>     window.outputlabel.setMinimumHeight(21)
> else:
>     window.outputlabel.setMinimumHeight(27)
> ```
> 
> And with just fixing broken macOS check, this change now only affects non-macOS.

image

**Comment by Et0h** [comment]
Thanks for the additional testing and fixes. The updated version seems good to go! 👍

**Pull request merged**
