### PR TITLE
Update mpv json ipc vendor code

### PR DESCRIPTION
**Pull request by daniel-123**
Update to version 1.1.13 to hopefully address #322 fully.

### CODE REVIEW

**Comment by FichteFoll** [comment]
```
~/code/syncplay Ξ python syncplayClient.py
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
MPV failed with returncode 1.
MPV start failed.
Traceback (most recent call last):
  File "/home/fichte/code/syncplay/syncplay/vendor/python_mpv_jsonipc/python_mpv_jsonipc.py", line 418, in __init__
    self.mpv_process = MPVProcess(ipc_socket, mpv_location, **kwargs)
  File "/home/fichte/code/syncplay/syncplay/vendor/python_mpv_jsonipc/python_mpv_jsonipc.py", line 242, in __init__
    raise MPVError("MPV not started.")
syncplay.vendor.python_mpv_jsonipc.python_mpv_jsonipc.MPVError: MPV not started.
MPV failed with returncode 1.
MPV start failed.
Traceback (most recent call last):
  File "/home/fichte/code/syncplay/syncplay/vendor/python_mpv_jsonipc/python_mpv_jsonipc.py", line 418, in __init__
    self.mpv_process = MPVProcess(ipc_socket, mpv_location, **kwargs)
  File "/home/fichte/code/syncplay/syncplay/vendor/python_mpv_jsonipc/python_mpv_jsonipc.py", line 242, in __init__
    raise MPVError("MPV not started.")
syncplay.vendor.python_mpv_jsonipc.python_mpv_jsonipc.MPVError: MPV not started.
MPV failed with returncode 1.
MPV start failed.
Traceback (most recent call last):
  File "/home/fichte/code/syncplay/syncplay/vendor/python_mpv_jsonipc/python_mpv_jsonipc.py", line 418, in __init__
    self.mpv_process = MPVProcess(ipc_socket, mpv_location, **kwargs)
  File "/home/fichte/code/syncplay/syncplay/vendor/python_mpv_jsonipc/python_mpv_jsonipc.py", line 242, in __init__
    raise MPVError("MPV not started.")
syncplay.vendor.python_mpv_jsonipc.python_mpv_jsonipc.MPVError: MPV not started.
```

**Comment by Et0h** [comment]
I got the same error. It seems to work again if you bring back the env code by:
* replacing `def __init__(self, ipc_socket, mpv_location=None, **kwargs)` with `def __init__(self, ipc_socket, mpv_location=None, env=None, **kwargs):` and
* replacing `self.process = subprocess.Popen(args)` with `self.process = subprocess.Popen(args, env=env)`

Also, because `ipc_iina.py` relies on `syncplay.vendor.python_mpv_jsonipc.python_mpv_jsonipc` it is possible that @albertosottile would need to update `class IINAProcess(MPVProcess):` in line with any changes to the vendor code.

**Comment by albertosottile** [comment]
To keep our modifications intact, I followed an inverted approach. I went to a Syncplay commit in which the vendor dependency had not been updated yet and compared the module in our code with version 1.1.13. Then, I went back to `master` and applied the same changes to our updated copy of the dependency. 

In the end, I compared the diffs between the two cases confirming that the vendor dependency was patched as desired. A quick verification can be done comparing the changes in this PR with the changes upstream from here https://github.com/iwalton3/python-mpv-jsonipc/compare/v1.1.11...v1.1.13.

I can confirm that I can correctly run IINA with the code in this branch. I would ask you all to confirm that you can also run mpv on your platforms.

Side note: VSCode automatically stripped some whitespace, hence why the diff shows these extra changes.

**Review by Et0h — APPROVED** [review]
Tested and it works fine for me on Windows 10 with mpv and mpv.net.

**Pull request merged**
