### PR TITLE
Ported GUI code to Qt.py

### PR DESCRIPTION
**Pull request by alby128**
As discussed in #152 , this code ports all the graphic interface of Syncplay to [Qt.py](https://github.com/mottosso/Qt.py), a shim that supports all the major Qt bindings for Python using a common syntax, with limited exceptions.

Currently, the support has been limited to PySide2 and PySide, to avoid unnecessary complications in the code. Syncplay is able to operate with both bindings, and will prefer PySide2 (and Qt 5) over PySide (Qt 4). 

In this PR, the packaging code is not changed, so PySide1 is still the binding embedded in the .exe for Windows and in the .dmg for macOS. However, users that install Syncplay from sources can already install PySide2 and run the software on Qt 5.

The code included in this PR has already been tested on Windows 7 and macOS 10.11+, using VLC 2.2.6, VLC 3, and mpv. 

P.S. I realize that 64 commits are probably a lot, but this PR includes more than 2,000 lines added, so I thought that having those divided in some way would have been better than a single rebased commit. However, I leave this choice to you guys.

### CODE REVIEW

**Comment by Et0h** [comment]
Tried it on Windows 10 with PySide through PyCharm and it seemed to work fine. It'd be helpful if people with different set-ups could try it.

**Comment by Et0h** [comment]
@soredake @Uriziel @daniel-123 @Hamuko @winneon @cartr @Hummer12007 : Can you please test this PR and report back on what OS and version of PySide you tested and if it works (including the file open dialogue from within the main Syncplay GUI).

**Comment by soredake** [comment]
Gentoo, pyside1, works.

**Comment by Hummer12007** [comment]
@soredake wanna try pyside2 from the qt overlay as well?

**Comment by soredake** [comment]
@Hummer12007 still can't build it https://bugs.gentoo.org/624682#c13

**Comment by Hummer12007** [comment]
Oh, I see. :(

**Comment by alby128** [comment]
@soredake If you want, Anaconda provides binaries for a dev snapshot of PySide2 on Qt 5.6. You can find those (and how to install them) here: https://anaconda.org/conda-forge/pyside2

**Comment by soredake** [comment]
Tested basic functions like joining channel and opening file with pyside2, seems working.

**Comment by Et0h** [comment]
@alby128 Do you know of any outstanding or likely issues or is it good to merge as far as you are aware?

**Comment by alby128** [comment]
I am not aware of any outstanding issues, so, as far as I know, this is ready to merge.

**Pull request merged**
