### PR TITLE
German Translation

### PR DESCRIPTION
**Pull request by DerGenaue**
This makes better sense

### CODE REVIEW

**Comment by nilsding** [comment]
This translation seems accurate.  The "comment" in `build2exe.py` on line 105 is imho unnecessary (and IIRC not a valid NSIS comment).

**Comment by Et0h** [comment]
Yes, the proposed comment on line 105 results in the following error:
>Traceback (most recent call last):
>   File "/syncplay/buildPy2exe.py", line 608, in compile
>    raise RuntimeError("NSIS compilation return code: %d" % retcode)
>RuntimeError: NSIS compilation return code: 1

**Comment by DerGenaue** [comment]
Oops, now I get it;
My fault; I'm used to work with Java and other Languages and I keep mixing up the syntax.
The editor highlights it => I'm done here

**Comment by DerGenaue** [comment]
By the way: what's IIRC and NSIS?

**Comment by Et0h** [comment]
Ah, sorry for not being more clear. 'IIRC' means 'If I Recall/Remember Correctly' and NSIS means 'Nullsoft Scriptable Install System' (i.e. what Syncplay uses for making Windows installers).

**Pull request merged**
