### PR TITLE
Improve playlist advancement for VLC and mpv (#334)

### PR DESCRIPTION
**Pull request by Et0h**
This change is intended to improve the reliability of playlist advancement in VLC and mpv.

This is achieved in two separate ways:
* For **mpv**, Syncplay now detects when the 'eof-reached' property in mpv is set to true.
* For **VLC**, Syncplay now detects changes to duration when playing from a URL (which was previously stuck at 0:00 if duration was not detected after a short delay when the YouTube video etc was opened) which allows it to more reliably detect EOF (end of file). This does result in a file change message to appear when the duration is updated. If this really bothers anyone then they can make a PR which hides that message.

**PLEASE TEST THIS AND LET ME KNOW IF THINGS WORK WELL FOR PLAYLIST ADVANCEMENT FOR BOTH FILES AND STREAMS (YOUTUBE) FOR MPV AND VLC.**

Because this required changes to both the Syncplay-side code and the player-side code I will leave this pull request open longer than usual to give people time to test this and let me know if it works or if it creates new problems.

Note: If you are alone in the room then by default Syncplay should advance to the next item in the playlist but should not start playing it.

You can download a portable version of this PR for Windows from: https://ci.appveyor.com/api/buildjobs/l41deaa3lo5kbwrb/artifacts/Syncplay_1.6.8_Portable.zip

### CODE REVIEW

**Comment by Canageek** [comment]
We are having trouble testing due to issues likely with youtube-dl: We've not been able to get youtube videos to work at all for a long time (months) have have switched to downloading the files with youtube-dl separately then watching them.  This is what happened when we went to test this release: The issue seems to be with youtube or youtube-dl as it happened between syncplay updates (ie no one had changed their syncplay version)

If you have any advice on getting it working I'll start doing testing

image

**Comment by Et0h** [comment]
Have you managed to test this @Canageek and @nnamrrehdlopoel ?

**Comment by Canageek** [comment]
Spent an evening testing with a friend with both Syncplay programs set to use VLC, and that worked perfectly. Will try with other clients soon.

**Comment by Et0h** [comment]
> Spent an evening testing with a friend with both Syncplay programs set to use VLC, and that worked perfectly. Will try with other clients soon.

Thanks for testing. Were you trying YouTube videos in VLC or just regular files?

**Comment by Canageek** [comment]
With youtube videos, should we also test files? 

I've got mpv, mpv.net, Media Player Classic: Black Edition, and VLC set up and ready for testing.

**Comment by Et0h** [comment]
> With youtube videos, should we also test files?

Testing with both would be ideal.

> 
> I've got mpv, mpv.net, Media Player Classic: Black Edition, and VLC set up and ready for testing.

I don't think I made any changes to the MPC code but nothing wrong with testing it. I'm not sure if there is proper YouTube handling for MPC-BE.

**Comment by Canageek** [comment]
mpv.net/mpv.net
Testing setup: <player one on desktop>/<player two on laptop>. Both connected to internet over the same connection (desktop wired, laptop wifi) so likely connecting to the same area of Youtube's CDN. The latest version of mpv.net and youtube-dl has been installed.

Had video playing on both laptop and desktop. On Desktop right-clicked on second video in playlist and selected Open Media Stream URL. Desktop started playing this right away. Laptop took several seconds to catch up with the change, and reset video back to the start twice before both were in sync.

On advancement from 2nd to 3rd video in playlist got the following messages: 
[12:13:14] Connection with server timed out
[12:13:14] Storm-Laptop has left
The laptop shows a Connection with server timed out error.
Could no longer continue testing with this session
Moved to Syncplay:8996 after this

After this video both desktop and laptop got "[12:19:39] Connection with server timed out" (laptop timestamp was 12:19:42)

**Comment by Canageek** [comment]
vlc/--
With only one client connected to the room VLC advanced smoothly to the next video (tested as I was installing updates to VLC on the other computer)

**Comment by Canageek** [comment]
vlc/vlc (laptop/desktop) advanced from video 1 on playlist to video 2 on playlist smoothly.

**Comment by Canageek** [comment]
mpv/mpv, 

mpv 0.33.0-88-gd1be8bb606 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Feb 28 09:25:17 +08 2021
FFmpeg library versions:
   libavutil       56.66.100
   libavcodec      58.126.100
   libavformat     58.68.100
   libswscale      5.8.100
   libavfilter     7.107.100
   libswresample   3.8.100
FFmpeg version: git-2021-02-28-85ab9deb

Same issue as mpv.net, [13:17:45] Connection with server timed out

**Comment by Canageek** [comment]
Going to stop testing until that error is fixed, then I'll work on mpv/mpv.net, vlc/mpv, and vlc/mpv.net at the very least

**Comment by Et0h** [comment]
Are there any relevant errors in %APPDATA%/.syncplay.log?

The mpv issue with the playlist might be resolved by #400 so when that's merged we can update this accordingly.

**Comment by Canageek** [comment]
So, .syncplay.log was in the Syncplay_1.6.8_Portable folder. However, it had a bunch of stuff in there from when I tried to use mplayer that was unrelated, so I deleted it and tried this again. Only one client connected to the room, using the same version of mpv.net as last time. 

Same set of errors: 

[12:31:44] <name> jumped from 00:00 to 00:00
[12:31:44] <name> paused
[12:31:56] Connection with server timed out

and no log was generated in Syncplay_1.6.8_Portable this time.

**Comment by Et0h** [comment]
@Canageek Could you please test https://github.com/Syncplay/syncplay/suites/2310287485/artifacts/48495030 and let me know if it fixes the issues you had with mpv.

**Comment by Et0h** [comment]
No issues have been removed about the update version of this PR, so I'll be merging this to allow for broader testing in advance of the a planned beta release (which will hopefully be around the 5th of April if everything goes smoothly).

**Comment by Canageek** [comment]
Sorry, I've been sick and just got to this today. Should I still test the linked version?

**Comment by Canageek** [comment]
With mpv 0.33.0-102-g5824d9fff8 and youtube-dl 2021.04.01 it no longer disconnects and does transition to the next video, BUT does goes back to pausing after each video. Tested with only one client connected to the room.

**Comment by Et0h** [comment]
@Canageek Thanks for your testing. It has now been merged into the main branch so the ideal version to test is the artefact from the latest commit which is https://github.com/Syncplay/syncplay/suites/2363843003/artifacts/50062530 but functionally it should be equivalent to testing the one I posted 13 days ago.

In terms of not unpausing when you change file, as per https://github.com/Syncplay/syncplay/issues/315 it is expected behaviour that the auto-advancement will not result in an auto-play if you are the only one in the room:
> **Get to the end of a file with shared playlists are enabled** It advances to the next file, resets to 0:00. Then auto-plays after 3 seconds unless someone in the room is set to not being 'ready' **_(or unless you are the only one in the room)_**. **_(emphasis added)_**

**Comment by Canageek** [comment]
Have tested this for one morning with mpv on two computers, and one with mpv.net on two computers. This now advances as expected.

**Comment by Et0h** [comment]
> Have tested this for one morning with mpv on two computers, and one with mpv.net on two computers. This now advances as expected.

That is fantastic news. I look forward to including the improvements in the forthcoming release!

**Pull request merged**
