### PR TITLE
Added Simplified Chinese Translation.

### PR DESCRIPTION
**Pull request by lryanner**
Added Simplified Chinese Translation.

### CODE REVIEW

**Comment by Et0h** [comment]
Hi, is this based on the work at https://github.com/Syncplay/syncplay/issues/495 or is it a completely separate effort?

**Comment by lryanner** [comment]
It is a completely separate effort.

**Comment by Et0h** [comment]
@Zhaodaidai Can you please check this translation and let me know if there are any changes to lryanner's translation that are needed or if it is ready for my to accept?

You can try it out at https://github.com/Syncplay/syncplay/actions/runs/1765082375 with the installer available from https://github.com/Syncplay/syncplay/suites/5105697623/artifacts/152965407

**Comment by Et0h** [comment]
@[Zhaodaida](https://github.com/Zhaodaidai) said they were very satisfied with this translation over #495 and I've tested it and it seems to work fine for me so I'm approving this translation. Thank you for your work on this!

**Comment by lryanner** [comment]
I'm glad to know that my work is merged into master. And I will continue to support Syncplay project.

**Pull request merged**
