### PR TITLE
Use ca configuration if defined

### PR DESCRIPTION
**Pull request by kidburglar**
It let the user push his own CA to syncplay by override certPath.

I saw that certifi.where() use his own cacert bundle, it can be usefull to use another one. It also fixed the second scenario of #248 when we use a self-signed certificate with a custom CA.

### CODE REVIEW

**Comment by kidburglar** [comment]
Hello @daniel-123 I think certifi use his own bundled CA and not the system one.
If I'm right it mean there is no way to properly manage your own CA. That is a big trouble because it result to manage 2 CA bundled and the need to do it properly.

Let me know if I'm wrong about certifi CA bundle.
Cheers.

**Comment by daniel-123** [comment]
Right now Syncplay uses the CA bundle that's returned by certifi.where()

At least on Debian and Fedora that returns path to system CA bundle, I'm not sure about other distributions. On Windows and Mac it indeed uses the CA bundle delivered by certifi.

Back to my question - I still do not see any reasonably typical use case for manually switching to a different CA bundle. I get that this is somewhat common functionality in enterprise software, but Syncplay isn't really aiming at being that.

**Comment by kidburglar** [comment]
Maybe it's related if it's installed by the system or by --user flag but in my case it didn't use the system one, output for python2 and python3.

```
>>> import certifi.where()
>>> import certifi
>>> certifi.where()
'/home/user/.local/lib/python2.7/site-packages/certifi/cacert.pem'
```

```
>>> import certifi
>>> certifi.where()
'/home/user/.local/lib/python3.7/site-packages/certifi-2019.6.16-py3.7.egg/certifi/cacert.pem'
```

Simply if we not want to make a register though letsencrypt. With the output above it could lead to another issue if by bad luck we use a certificate that the CA is not recognized by the CA bundle.

**Comment by daniel-123** [comment]
The problem I have with that use case, is that it requires you to ensure that your custom certificate root needs to be added to each and every client you want to have connected to your server. This is done on regular basis in enterprise environment by using Group Policies on Windows, but I don't think it makes much sense outside of that specific context.

**Comment by kidburglar** [comment]
I just checked the project python-certifi and they clearly show that it use his own CA.
It's something that can maybe work pretty well on Windows but on Linux there is a reason that we have a system CA. It's more easy to be manage but also for security concerns it's more easier.

Based on what I see when I use SSL for websites, we always receive the CA with our certificates. I think that the main reason it is given, it's because it's always possible that our bundle not have that CA.

**Comment by daniel-123** [comment]
After some poking around I see why certifi.where() it's different for you. On my system I use certifi from repositories which differs from upstream and actually points towards system CA. Is this an option for you?

>it's always possible that our bundle not have that CA.

I'm not sure if I understand. Standard CA bundles (like Mozilla one used by certifi, or default one in Debian) are all pretty much the same.

Only reason to add a CA to them is if you have your own one. And in that case certificates signed by that CA will not show up as trusted in web browser unless that CA was specifically added to the bundle given browser uses (Chrome and Edge use system CA, but Firefox does not).

>It's something that can maybe work pretty well on Windows but on Linux there is a reason that we have a system CA.

I know this is somewhat offtopic nitpicking, but it's actually the other way around. Windows does have a single standard CA bundle while Linux does not. Linux distributions usually have some semblance of system-wide CA, but you cannot actually rely on it being there.

**Comment by kidburglar** [comment]
> After some poking around I see why certifi.where() it's different for you. On my system I use certifi from repositories which differs from upstream and actually points towards system CA. Is this an option for you?

I confirm that using the repositories make it use the system bundle. For me it's ok then.
> 
> > it's always possible that our bundle not have that CA.
> 
> I'm not sure if I understand. Standard CA bundles (like Mozilla one used by certifi, or default one in Debian) are all pretty much the same.
> 
> Only reason to add a CA to them is if you have your own one. And in that case certificates signed by that CA will not show up as trusted in web browser unless that CA was specifically added to the bundle given browser uses (Chrome and Edge use system CA, but Firefox does not).
> 
> > It's something that can maybe work pretty well on Windows but on Linux there is a reason that we have a system CA.
> 
> I know this is somewhat offtopic nitpicking, but it's actually the other way around. Windows does have a single standard CA bundle while Linux does not. Linux distributions usually have some semblance of system-wide CA, but you cannot actually rely on it being there.

I would still advice a little note about which bundled is used in the documentation so if someone need to add his own CA there an he not use the system bundle he still can do it on his own.

**Pull request closed without merging**
