### PR TITLE
Turkish language translations added

### PR DESCRIPTION
**Pull request by muaz742**
I could not understand how to add language option to the project codes. But I translated messages to Turkish from English.

### CODE REVIEW

**Comment by muaz742** [comment]
Thank you for explaining.

I reviewed the commit and worked according to the commit. I hope benefit.

**Comment by Et0h** [comment]
Thank you. I will need to review it but it looks good. Thank you for your work on this.

**Comment by Et0h** [comment]
Checked and the PR is fine to merge but two post-merge tweaks are needed:
1. Make the 'start menu' checkbox in the installer slightly wider so that it fits the message.
2. Update messages to add reference to the new IINA support recently added in #360

I also noticed that the order of most of the languages are different in the installer and in Syncplay itself, so I might want to tweak Syncplay to use the same alphabetical order as the installer.

**Comment by Et0h** [comment]
I've done those changes:
1. Widen Windows installer start menu checkbox for Turkish translation: 628a233145653f0939f74dcbe28d83d606c24d63
2. Update Turkish translation for IINA:  2923fade0938790a6da1cf2c502e02a6989dded2
3.  Make language list alphabetical for consistency: 1644eec34b0e5d2654a83927fe5bc4b744b32d14

**Pull request merged**
